from pyspark.sql import functions as f
from pyspark.sql.types import DecimalType


def build_category_performance(orders_df, order_items_df, products_df):
    # Only completed orders generate sales metrics
    completed_orders_df = orders_df.filter(f.col("status") == "completed")

    # Connect orders with their line items
    sales_df = completed_orders_df.join(
        order_items_df,
        on="order_id",
        how="inner",
    )

    # Add product category
    sales_df = sales_df.join(
        products_df.select(
            "product_id",
            "category",
        ),
        on="product_id",
        how="inner",
    )

    # Revenue generated by a single order item
    sales_df = sales_df.withColumn(
        "line_revenue",
        f.col("quantity") * f.col("unit_price"),
    )

    # One Gold row represents one category
    category_performance_df = sales_df.groupBy("category").agg(
        f.countDistinct("order_id").alias("order_count"),
        f.sum("quantity").alias("items_sold"),
        f.sum("line_revenue").alias("revenue"),
    )

    # Stable financial schema
    category_performance_df = category_performance_df.withColumn(
        "revenue",
        f.col("revenue").cast(DecimalType(18, 2)),
    )

    # Average actual selling price per item
    category_performance_df = category_performance_df.withColumn(
        "average_selling_price",
        (f.col("revenue") / f.col("items_sold")).cast(DecimalType(18, 2)),
    )

    return category_performance_df
