from pyspark.sql import functions as f
from pyspark.sql.types import DecimalType


def build_customer_metrics(orders_df, order_items_df, customers_df):
    # Only completed orders count toward customer sales metrics
    completed_orders_df = orders_df.filter(f.col("status") == "completed")

    # Connect completed orders with their line items
    sales_df = completed_orders_df.join(
        order_items_df,
        on="order_id",
        how="inner",
    )

    # Revenue generated by a single order item
    sales_df = sales_df.withColumn(
        "line_revenue",
        f.col("quantity") * f.col("unit_price"),
    )

    # One Gold row represents one customer
    customer_metrics_df = sales_df.groupBy("customer_id").agg(
        f.countDistinct("order_id").alias("order_count"),
        f.sum("quantity").alias("items_bought"),
        f.sum("line_revenue").alias("total_spent"),
        f.min("order_date").alias("first_order_date"),
        f.max("order_date").alias("last_order_date"),
    )

    # Keep financial metrics on a stable schema
    customer_metrics_df = customer_metrics_df.withColumn(
        "total_spent",
        f.col("total_spent").cast(DecimalType(18, 2)),
    )

    # Average value of one completed order
    customer_metrics_df = customer_metrics_df.withColumn(
        "average_order_value",
        (f.col("total_spent") / f.col("order_count")).cast(DecimalType(18, 2)),
    )

    # Add current customer attributes from Silver
    customer_metrics_df = customer_metrics_df.join(
        customers_df.select(
            "customer_id",
            "first_name",
            "last_name",
            "country",
        ),
        on="customer_id",
        how="left",
    )

    return customer_metrics_df
