from pyspark.sql import functions as f


def build_product_performance(orders_df, order_items_df, products_df):
    # Only completed orders generate sales metrics
    completed_orders_df = orders_df.filter(f.col("status") == "completed")

    # Connect orders with their line items
    sales_df = completed_orders_df.join(
        order_items_df,
        on="order_id",
        how="inner",
    )

    # Revenue generated by a single order item
    sales_df = sales_df.withColumn(
        "line_revenue",
        f.col("quantity") * f.col("unit_price"),
    )

    # Add product attributes used in Gold analytics
    sales_df = sales_df.join(
        products_df.select(
            "product_id",
            "name",
            "category",
        ),
        on="product_id",
        how="inner",
    )

    # One Gold row represents one product
    product_performance_df = sales_df.groupBy(
        "product_id",
        "name",
        "category",
    ).agg(
        f.countDistinct("order_id").alias("order_count"),
        f.sum("quantity").alias("items_sold"),
        f.sum("line_revenue").alias("revenue"),
    )

    # Average actual selling price per item
    product_performance_df = product_performance_df.withColumn(
        "average_selling_price",
        f.round(
            f.col("revenue") / f.col("items_sold"),
            2,
        ),
    )

    return product_performance_df
